PeggyJV/gravity-bridge

module/proto/gravity/v1/query.proto
orchestrator/Cargo.lock
orchestrator/cosmos_gravity/Cargo.toml
orchestrator/cosmos_gravity/src/query.rs
orchestrator/cosmos_gravity/src/send.rs
orchestrator/ethereum_gravity/src/logic_call.rs
orchestrator/gravity_proto/src/prost/gravity.v1.rs
orchestrator/gravity_utils/src/connection_prep.rs
orchestrator/gravity_utils/src/message_signatures.rs
orchestrator/gravity_utils/src/types/batches.rs
orchestrator/gravity_utils/src/types/ethereum_events.rs
orchestrator/gravity_utils/src/types/logic_call.rs
orchestrator/gravity_utils/src/types/mod.rs
orchestrator/gravity_utils/src/types/valsets.rs
orchestrator/orchestrator/src/ethereum_event_watcher.rs
orchestrator/orchestrator/src/main_loop.rs
orchestrator/relayer/src/logic_call_relaying.rs

Rebases and Squashes #19 for a clean merge.

Regenerate rust code from proto files.

---

module/x/gravity/keeper/cosmos_originated.go
orchestrator/cosmos_gravity/src/send.rs
orchestrator/test_runner/src/happy_path_v2.rs
testnet/start.sh

Small changes required to get the V2_HAPPY_PATH e2e test fixes.
- needed denom metadata setup in genesis
- needed to update message names in Rust

V2_HAPPY_PATH e2e test fixes

---

module/x/gravity/keeper/keeper.go
module/x/gravity/keeper/keeper_test.go

Remove the nil ethsigner addresses from valset

---

orchestrator/cosmos_gravity/src/send.rs
orchestrator/gorc/gorc.toml
orchestrator/gorc/src/commands.rs
orchestrator/gorc/src/commands/orchestrator/start.rs
orchestrator/gorc/src/config.rs
orchestrator/orchestrator/src/main.rs
orchestrator/orchestrator/src/main_loop.rs
orchestrator/test_runner/src/happy_path.rs
orchestrator/test_runner/src/main.rs

gorc config gas prices take

---

orchestrator/Cargo.lock
orchestrator/cosmos_gravity/src/build.rs
orchestrator/gorc/gorc.toml
orchestrator/gorc/src/commands.rs
orchestrator/gorc/src/commands/orchestrator/start.rs
orchestrator/gorc/src/config.rs
orchestrator/orchestrator/Cargo.toml
orchestrator/orchestrator/src/ethereum_event_watcher.rs
orchestrator/orchestrator/src/lib.rs
orchestrator/orchestrator/src/main.rs
orchestrator/orchestrator/src/main_loop.rs
orchestrator/orchestrator/src/metrics.rs
orchestrator/test_runner/src/happy_path.rs

Prometheus metrics for the orchestrator

---

orchestrator/gorc/src/commands/eth_to_cosmos.rs

@hannydevelop -- I'll use this PR to provide feedback on #138 
Will keep it in draft mode until I'm done reviewing.

gorc eth-to-cosmos feedback on #138

---

orchestrator/gorc/src/commands/cosmos_to_eth.rs

@hannydevelop I'm creating a PR against your branch / PR  #119 to provide feedback. I'll:
- keep this in draft until I am "done"
- try to keep my commit messages clear to identify each issue
- mark this as "Ready for Review" and add you as a Reviewer shortly

gorc cosmos-to-eth feedback on #119

---

orchestrator/cosmos_gravity/src/send.rs
orchestrator/relayer/src/valset_relaying.rs

- valset log is wayyyy to noisy
- removed redundant TODO that was addressed

log housekeeping

---

orchestrator/cosmos_gravity/src/build.rs
orchestrator/gravity_utils/src/types/ethereum_events.rs
orchestrator/gravity_utils/src/types/valsets.rs
orchestrator/orchestrator/src/ethereum_event_watcher.rs
orchestrator/orchestrator/src/main_loop.rs
orchestrator/orchestrator/src/oracle_resync.rs

* Update our internal `ValsetUpdatedEvent` to match the expected structure (old version didn't cause errors but is a bit inconsistent and confusing)
* Get the block delay based on our chain ID before we start the main loop rather than doing it over and over
* Fix up some comments and logging messages

Assorted code improvements

---

module/x/gravity/abci.go
module/x/gravity/keeper/batch.go

Bug found in our testnet. All nodes got stopped by a nil pointer exception
See comment below

Fix bug on cleaning batch

---

orchestrator/cosmos_gravity/src/query.rs

If an invalid batch somehow makes it on chain, in theory if we just have the orchestrator ignore it it will eventually time out and be canceled. This PR will filter out anything that doesn't cleanly serialize from the proto when querying for current batches against the chain. Ideally we also address this on the chain side, but this will prevent the orchestrator from throwing errors in the meantime.

Only process valid transaction batches

---

orchestrator/gorc/src/commands/sign_delegate_keys.rs

should be `gorc sign-delegate-keys $key_name $val_address $nonce`

fix sign-deletate-keys command parameters

---

orchestrator/gorc/src/commands/cosmos_to_eth.rs

Don't request a transaction batch unless there were successful transfers of Cosmos tokens.

Only trigger a batch if there were sends

---

module/x/gravity/client/cli/tx.go

Small bugfix for the command line

Fix cancelSendToEth cmd arguments

---

orchestrator/relayer/src/main.rs

fix small typo in relayer command

---

.github/workflows/integration-tests.yml
Makefile
integration_tests/ethereum.go
integration_tests/setup_test.go
integration_tests/valset_stress_test.go

This PR is a work in progress. We're moving tests from the `testnet` module into the `integration_test` suite. The tests from `testnet` module are outdated and don't work properly. We're refining these tests for gravity-bridge to make sure they work as expected in the `integration_test` suite

Integration test suite update

---

module/x/gravity/types/key.go

This file contain a lot of comments with misleading values.

Fix comments in key.go

---

integration_tests/happy_path_test.go
module/x/gravity/keeper/batch.go
module/x/gravity/keeper/keeper.go
orchestrator/cosmos_gravity/src/build.rs

Also fix type URLs for unsigned batches/contract calls in the orchestrator

Include chain id for new Batch/ContractCall

---

module/x/gravity/types/msgs.go

Implement GetSignBytes() for gravity Msgs

---

module/x/gravity/types/codec.go

Add missing amino registrations

Add missing amino registrations

---

module/x/gravity/keeper/keeper.go

Problem: Some operation loops over the entire storage

---

.github/workflows/automated-release.yml

Add content write permissions for automated release

Add content write permissions for automated release

---

module/app/export.go

to align with [sdk](https://github.com/cosmos/cosmos-sdk/blob/3a7a2645f05f0aecdf96ebda14a7c62f6d4ddc55/simapp/export.go#L80) export

avoid fatal on no validator commission to withdraw
