PeggyJV/gravity-bridge

- module/x/gravity/handler.go
- module/x/gravity/keeper/grpc_query.go
- module/x/gravity/keeper/msg_server.go
- module/x/gravity/types/msgs.go
- orchestrator/cosmos_gravity/src/send.rs
- orchestrator/gravity_utils/src/types/valsets.rs
- orchestrator/relayer/src/valset_relaying.rs
- orchestrator/test_runner/src/happy_path.rs
We "fixed" this by commenting out the test code which was supposed to test whether valsets (signer sets in the new nomenclature) get updated. We will revisit it once we have a gRPC library to hit the delegate endpoint for us because this is what triggers signer set updates.
> Fix valset stuck at 1

- .dockerignore
- docker-compose.yml
- module/Dockerfile
- testnet/reup-gravity.sh
- testnet/start.sh
Introduced `./testnet/reup-gravity.sh` to stop, build and start gravity nodes in the testnet to improve debug cycles.
Required loosening declared start-up dependencies w/in the docker-compose file; so I confirmed that our start script brings everything up from scratch still.
Also improved `module/Dockerfile` to cache go deps more effectively, so we don't download them everytime.
> script to "reup" testnet gravity nodes

- .github/workflows/integration-tests.yml
- module/proto/gravity/v1/query.proto
- module/x/gravity/abci.go
- module/x/gravity/keeper/keeper.go
- module/x/gravity/types/types_test.go
- orchestrator/Cargo.lock
- orchestrator/cosmos_gravity/src/query.rs
- orchestrator/ethereum_gravity/src/valset_update.rs
- orchestrator/relayer/src/main_loop.rs
- orchestrator/relayer/src/valset_relaying.rs
- orchestrator/test_runner/Cargo.toml
- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/happy_path_v2.rs
- orchestrator/test_runner/src/main.rs
- orchestrator/test_runner/src/valset_stress.rs
- testnet/start.sh
This PR stabilizes the VALSET_STRESS end-to-end test. 
These tests are not yet runnable via GitHub actions / CI. 
To run them manually, the current practice is:
```bash
$ pushd module/ && make install && popd # to ensure you have an up-to-date `gravity` binary
$ docker-compose down && sudo rm -fr testdata && TEST_TYPE=VALSET_STRESS ./start-testnet.sh # to ensure a pristine test-run
```
> VALSET_STRESS end-to-end test fixes

- orchestrator/Cargo.lock
- orchestrator/gravity_utils/src/types/signatures.rs
This started as an optimistic clarity upgrade
-version = "0.4.5"
+version = "0.4.10"
Then cherry-picked this deep-fix from Justin:
https://github.com/althea-net/cosmos-gravity-bridge/commit/d752ed0639bdbb61641599f7afa091a0046731e3
> Fix "Validator signature does not match." errors

- docker-compose.yml
- orchestrator/gravity_utils/src/types/ethereum_events.rs
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- testnet/start.sh
Fixes for the following; which occurs intermittently, but regularly:
```
check_for_events send_ethereum_claims response TxResponse { height: 37, txhash: "D19947B0CB9A3801C458E20B60C5AC533BD115ED11C714333FDED33B6FDAB02E", codespace: "gravity", code: 3, data: "", raw_log: "failed to execute message; message index: 0: create event vote record: non contiguous event nonce expected 4 observed 3 for validator 83A7E562DF8662B1BDB47FF0E74390E7FF320CDD: invalid", logs: [], info: "", gas_wanted: 500000000, gas_used: 55933, tx: Some(Any { type_url: "/cosmos.tx.v1beta1.Tx", value: [...] }), timestamp: "2021-06-17T14:53:21Z" }
```
> fix non contiguous event nonce errors

- module/go.sum
- module/x/gravity/abci.go
- module/x/gravity/keeper/ethereum_event_vote.go
- module/x/gravity/keeper/keeper.go
Refactor logger to be public so logic, e.g. ABCI methods with access to the keeper, can log correctly.
> x/gravity: logger

- module/Makefile
The proto-breakage action would always fail, because it depended on an env var that was unset. This should make it work.
> Proto-breakage action fix

- orchestrator/gorc/src/commands/keys/cosmos.rs
- orchestrator/gorc/src/commands/keys/cosmos/add.rs
- orchestrator/gorc/src/commands/keys/cosmos/recover.rs
- orchestrator/gorc/src/commands/keys/eth.rs
- orchestrator/gorc/src/commands/keys/eth/import.rs
- orchestrator/gorc/src/commands/keys/eth/list.rs
- orchestrator/gorc/src/commands/keys/eth/recover.rs
- orchestrator/gorc/src/commands/keys/eth/show.rs
This renames two existing sub-commands and adds one new command. The goal of this change is to let us work directly with eth private keys; since that's how we originally configured things, pre-gorc.
Rename 1:
`gorc keys cosmos import [name] (bip39-mnemonic)` is now 
`gorc keys cosmos recover [name] (bip39-mnemonic)`
Rename 2:
`gorc keys eth import [name] (bip39-mnemonic)` is now 
`gorc keys eth recover [name] (bip39-mnemonic)`
Addition 1:
`gorc keys eth import [name] (private-key)` exists. 
```bash
$ ## manually removing my keystore
$ rm -fr /tmp/keystore && mkdir /tmp/keystore
$ ## list all keys; confirm there are none
$ cargo -q run -- keys eth list --show-private-key
$ ## add an eth key
$ cargo -q run -- keys eth add eth-k1 --show-private-key
**Important** record this bip39-mnemonic in …
```
> gorc: disambiguate recover & import; introduce `gorc keys eth import`

- testnet/validator.go
Should fix the halt in the CI tests.
> Hash eth msg before signing in validator.go

- module/x/gravity/keeper/ethereum_event_handler.go
- module/x/gravity/types/errors.go
Support tokens w/o metadata, e.g. IBC tokens, by default to zero decimals.
> x/gravity: support tokens without metadata

- module/app/app.go
- module/go.mod
- module/go.sum
- testnet/go.mod
- testnet/go.sum
Bump SDK v0.43 to rc3. This is likely the last RC and includes the IBC fix.
> Bump SDK v0.43

- module/app/address.go
- module/app/app.go
- module/cmd/gravity/cmd/root.go
- module/x/gravity/types/msgs_test.go
In order for an upstream application that wants to use any of the Gravity Bridge's commands or CLI functionality, the SDK configuration cannot be done in any `init` call, otherwise the SDK will panic as the config will be sealed.
This means that the gravity bridge will have to call the SDK configuration setting elsewhere outside of an `init`. A good enough place is in the root command constructor.
> Refactor SDK Configuration

- solidity/contracts/Gravity.sol
This is almost definitely not necessary but better safe than sorry
(cherry picked)
> Add nonReentrant modifier to updateValset

- orchestrator/Cargo.lock
- orchestrator/gorc/Cargo.toml
Update deep space fork to remove no_token error
> Update deep_space fork

- orchestrator/Cargo.lock
- orchestrator/gorc/Cargo.toml
Update to the version of deep space that treats non-zero return codes as errors
> Update to the version of deep space

- orchestrator/cosmos_gravity/src/send.rs
Closes #260 
Ensures that the `amount` and `bridge_fee` denominations match inside of the `send_to_eth()` method.
> Denomination sanity check in send_to_eth()

- module/x/gravity/keeper/ethereum_event_vote.go
Copy the events from the cache context to the original context, otherwise they will be ignored
> Fix EthereumEventProcessor events

- module/x/gravity/keeper/keeper.go
- module/x/gravity/keeper/keeper_test.go
This pull request adds supporting infrastructure for cleaning up state and  migrating to new gravity contract.
It does not add the transactions to migrate cosmos ERC20 tokens to the new bridge:
> Add a migrate function to the keeper to clean up state to move to a new gravity contract

- module/x/gravity/keeper/keeper.go
- module/x/gravity/keeper/keeper_test.go
In addition to resetting the keeper's last observed event nonce, reset the value for each individual validator, as the oracle resync orchestrator process is retrieving the last event nonce attached to its own address.
> Reset last ethereum event for each validator

- module/x/gravity/keeper/keeper.go
- module/x/gravity/keeper/keeper_test.go
* Make sure we only delete all ethereum events after reading them so we can correctly zero out event nonces
* Return false in the `iterateEthereumEventVoteRecords` function, or it will stop early after the first record
* In the keeper test, make sure we set the event nonces manually so the test will fail if it's not functioning correctly, and also test presence for all ethereum event records
> Fix migration ethereum nonce reset per validator

- orchestrator/ethereum_gravity/src/send_to_cosmos.rs
- orchestrator/gorc/src/commands/eth_to_cosmos.rs
Fix argument parsing (amount needs to be parsed as a decimal string into U256) and force a legacy transaction since the manually set gas limit isn't respected in EIP1559 transactions.
> Fix the eth-to-cosmos command

- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/get_with_retry.rs
* Update our block delay to a somewhat safer value. Using 13 is still a bit low, but this mirrors what the Gravity Bridge chain is doing in production. We could choose to set a higher value as well, but 6 is too low in any case.
* The version of `ethers` we are pinned to implements `net_version` but appears to do it incorrectly, as it throws an error. As such, since we are claiming to rely on chain ID already anyway, we should use chain IDs rather than net versions in our check. Additionally, add the Hardhat chain ID to remove the block delay in our local test environment (maybe we can disable the autominer?)
> Update block delay, use chain ID correctly

- orchestrator/ethereum_gravity/src/deploy_erc20.rs
- orchestrator/ethereum_gravity/src/utils.rs
- orchestrator/gorc/src/commands/deploy/erc20.rs
- orchestrator/gravity_utils/src/ethereum.rs
- orchestrator/test_runner/src/happy_path_v2.rs
Add the option for a gas multiplier when deploying an ERC20. Contains some debugging cruft that will be removed before this is converted from a draft.
> Use gas multiplier for ERC20 deploy

- module/x/gravity/keeper/genesis.go
- module/x/gravity/keeper/genesis_test.go
- module/x/gravity/types/genesis.go
- module/x/gravity/types/genesis_test.go
Use a placeholder value for `EthSignature` in `DelegateKeys` when exporting since it will not be present in the keeper and will instead return `null`. Additionally, add testing to confirm `DelegateKeys` validation is working as expected.
> Fix and test delegate genesis export

- orchestrator/gorc/src/commands/deploy/erc20.rs
Based on testing, it may take longer than the existing 100 second timeout to fully deploy an ERC20. This won't cause the deploy to fail, as the timeout is querying the chain state, but it tells the user it failed. To verify it succeeded after a timeout one would need to query the gravity module using `denom_to_erc20` themselves.
> Deploy ERC20 waits longer due to block delay

- module/x/gravity/keeper/batch.go
- module/x/gravity/keeper/batch_test.go
- module/x/gravity/keeper/msg_server.go
- module/x/gravity/keeper/msg_server_test.go
This is a proposed chain-side fix for the issue resolved orchestrator-side in https://github.com/PeggyJV/gravity-bridge/pull/344
Calling `RequestBatchTx` when there were no waiting `SendToEthereum` transactions would cause the orchestrator throw errors that it had received an empty batch and it would get stuck. Additionally, I think (in a case we did not hit in test) if `BuildBatchTx` returned nil because a more profitable batch already existed, this could cause a nil pointer exception when the event is emitted.
> Reject bad batches in RequestBatchTx

- orchestrator/gorc/Cargo.toml
Latest tag still reports `v0.3.8`
> Update gorc version string

- solidity/package.json
Following this issue https://github.com/PeggyJV/gravity-bridge/issues/354 
Open a PR to fix this upstream.
We might need also to consider updating all dependencies to their latest version
> Fix solidity dev dependencies

- orchestrator/Cargo.lock
- orchestrator/Cargo.toml
- orchestrator/cosmos_gravity/Cargo.toml
- orchestrator/cosmos_gravity/src/build.rs
- orchestrator/cosmos_gravity/src/crypto.rs
- orchestrator/cosmos_gravity/src/lib.rs
- orchestrator/cosmos_gravity/src/send.rs
- orchestrator/ethereum_gravity/Cargo.toml
- orchestrator/gorc/Cargo.toml
- orchestrator/gorc/src/commands/tx/cosmos.rs
- orchestrator/gorc/src/config.rs
- orchestrator/gravity_utils/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/register_delegate_keys/Cargo.toml
- orchestrator/register_delegate_keys/src/main.rs
- orchestrator/relayer/Cargo.toml
- orchestrator/test_runner/Cargo.toml
- orchestrator/test_runner/src/bootstrapping.rs
- orchestrator/test_runner/src/happy_path.rs
- orchestrator/test_runner/src/happy_path_v2.rs
- orchestrator/test_runner/src/orch_keys_update.rs
- orchestrator/test_runner/src/utils.rs
- update deep_space with ethermint feature
- add a PrivateKey which switch to ethermint when ethermint feature is turn on
- change default hd_path if ethermint feature turn on
To build with ethermint feature run :
` cargo build --features ethermint `
> Support ethermint mode with features

- integration_tests/happy_path_test.go
- integration_tests/setup_test.go
The test you were setting up is meant to be an ERC20-originated denom test rather than the reverse. The chain also had no metadata for a cosmos "DDS" denom, only "testgb". Additionally, denoms should only be treated as cosmos-originated if they were deployed through the contract using the deploy ERC20 functionality.
This will still be broken, but will pass once the capitalization issue of contract strings is fixed on main.
> E2E bugfixes around ERC20-originated denoms

- module/x/gravity/abci_test.go
- module/x/gravity/cosmos_originated_test.go
- module/x/gravity/handler_test.go
- module/x/gravity/keeper/batch_test.go
- module/x/gravity/keeper/cosmos_originated.go
- module/x/gravity/keeper/ethereum_event_handler.go
- module/x/gravity/keeper/genesis.go
- module/x/gravity/keeper/grpc_query.go
- module/x/gravity/keeper/keeper_test.go
- module/x/gravity/keeper/msg_server.go
- module/x/gravity/keeper/msg_server_test.go
- module/x/gravity/keeper/pool.go
- module/x/gravity/keeper/pool_test.go
- module/x/gravity/keeper/test_common.go
- module/x/gravity/migrations/v1/key.go
- module/x/gravity/migrations/v1/store.go
- module/x/gravity/migrations/v1/store_test.go
- module/x/gravity/module.go
- module/x/gravity/types/ethereum.go
- module/x/gravity/types/key.go
It was discovered that inconsistent casing of ERC20 contract addresses was causing denomination mismatches when trying to send coins over the bridge. This PR does the following:
* Where possible, have functions take in `common.Address` types rather than strings
* When input is received either through the message server or in the Ethereum event handler, normalize references to denoms before using them to look up data in the keeper (e.g. messages sent with manually specified denoms in `sdk.Coin` or string literals)
* Change the keeper storage of the cosmos-originated ERC20-to-denom mapping to key off of `common.Address` bytes rather than string bytes (the opposite denom-to-ERC20 mapping was already doing this correctly, but by its nature creating a mismatch)
* Fix a bug in …
> Fix ERC20 address casing in denoms

- module/app/app.go
Forgot to include the client proposal handler in the instantiation of the gov module.
> Add gravity CLI proposal handler to gov module

- module/app/app.go
- module/app/upgrades/v2/README.md
- module/app/upgrades/v2/constants.go
- module/app/upgrades/v2/upgrades.go
- module/app/upgrades/v2/upgrades_test.go
- module/x/gravity/keeper/migrations.go
- module/x/gravity/keeper/test_common.go
- module/x/gravity/migrations/v1/store_test.go
- module/x/gravity/module.go
* Add the `govrouter` line for the new proposal that was missing
* Add the `Migrator` for the existing migration
* Set up the upgrade handler for v2 and update account balances with normalized denoms
> Upgrade handler, migrator, fix governance proposal

- module/cmd/gravity/cmd/root.go
Cmd registration happens automatically when passing an AppModule to
Gravity's ModuleManager constructor, this explicit registration in
txCommand() is unnecessary and confusing.
Ref
https://github.com/Gravity-Bridge/Gravity-Bridge/commit/8c46db11cd6f620a7b4a255dab87d212c35df411
> Fix vesting cli double-register

- orchestrator/ethereum_gravity/src/logic_call.rs
- orchestrator/relayer/src/logic_call_relaying.rs
- orchestrator/relayer/src/main_loop.rs
If we encounter a logic call that either returns an error when we relay it, or logically should not be relayed, we add it to a skip list to avoid attempting to process it in the future. When these calls would have been timed out based on the current Ethereum height plus a generous buffer to account for potential bridge inactivity, they are cleared from the skip list to prevent it from growing unbounded. Restarting the process will also clear the list, but should only risk repeating a failed transaction once per restart.
> Skip failing or invalid logic calls

- orchestrator/relayer/src/logic_call_relaying.rs
There are a few more error conditions where we must skip calls to not block the bridge.
> Add more logic call skips

- module/x/gravity/client/cli/tx.go
- module/x/gravity/types/codec.go
There was a line of boilerplate in `codec.go` for registering the proposal type that wasn't implemented.
> Register the community spend proposal correctly

- orchestrator/Cargo.lock
- orchestrator/gorc/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
- orchestrator/register_delegate_keys/Cargo.toml
- orchestrator/relayer/Cargo.toml
Because we updated the gravity module to `/v2`, even though it's awkward I think we have to jump to release 2.0.0 for it to resolve paths correctly. This bumps the cargo version of user-facing binaries that get built to 2.0.0 as well so their versions will reflect the release version.
This also bumps the rust version called out in `gorc`, as we are building with a later version in CI.
> Rust binary versions to say 2.0.0

- orchestrator/Cargo.lock
- orchestrator/gorc/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
- orchestrator/orchestrator/src/ethereum_event_watcher.rs
- orchestrator/orchestrator/src/main_loop.rs
If it has been a long time since the last confirmed event, in the existing code the oracle will try to search from that block to the latest block on the network. Depending on how far back that event is, it could be an enormous query. This change tries to chunk the search using our existing `blocks_to_search` config value. The `check_for_events` function will now only search that number of blocks forward, or to the latest block if that range is shorter. When this function successfully returns with `Ok(ending_block)`, the outer loop should set that as the new `last_checked_block` and move to the next chunk when the loop next iterates (the included code window is scrollable if it doesn't show the whole thing):
https://github.com/PeggyJV/gravity-bridge/blob/ed557f4b1e8f18f9817d86cf224cafb27ab9 …
> Search for oracle events in chunks

- module/cmd/gravity/cmd/gentx.go
The `gen-tx` cmd from cosmos-sdk generate messages specifying in the memo the validator address ip and node id 
https://github.com/cosmos/cosmos-sdk/blob/main/x/staking/client/cli/tx.go#L616
in the `collect-tx`, the memo is checked and rejected if it cannot find the validator network information
https://github.com/cosmos/cosmos-sdk/blob/main/x/genutil/collect.go#L128
Since the `gen-tx` cmd is overidden in gravity bridge, we need to follow the same logic and append the memo
> Fix gen-tx cmd

- module/x/gravity/abci.go
Comparison should be on the height.
This would cause unbounded validator not getting slashed for not signing during the unbound period
> Fix mistake on slashing logic

- orchestrator/ethereum_gravity/src/logic_call.rs
- orchestrator/ethereum_gravity/src/submit_batch.rs
- orchestrator/ethereum_gravity/src/valset_update.rs
- orchestrator/gorc/src/commands/orchestrator/start.rs
- orchestrator/gorc/src/config.rs
- orchestrator/orchestrator/src/main_loop.rs
- orchestrator/relayer/src/batch_relaying.rs
- orchestrator/relayer/src/logic_call_relaying.rs
- orchestrator/relayer/src/main.rs
- orchestrator/relayer/src/main_loop.rs
- orchestrator/relayer/src/valset_relaying.rs
This adds a CLI option for specifying an Ethereum gas limit multiplier, and converts relay contract calls into legacy versions to account for a bug in ethers that does not respect manually set gas limits in EIP1559 transactions.
Note that manually specified gas limits will always be overwritten if the access list estimate is lower:
https://github.com/iqlusioninc/ethers-rs/blob/4959552eb667ed2c765f6c0123bb0b7352cf948e/ethers-providers/src/lib.rs#L183-L204
> Specify gas limit multiplier for relaying

- .github/workflows/integration-tests.yml
- Makefile
- integration_tests/setup_test.go
- integration_tests/transaction_stress_test.go
Sends funds from ethereum over to cosmos and then back again, 100 total tx's in each direction.
Initially the plan was to create new accounts but it was too painful to get working so I reused the validator addresses since they're all configured and good to go.
> Add in Transaction Stress Test

- integration_tests/setup_test.go
Removing the data dir before taking down the Docker network fully can lead to scary "consensus errors" due to race conditions with file removal and node shutdown. This moves the deletion of the data dir to the end of teardown.
> Move removal of data dir to end of teardown

- integration_tests/gorc_bootstrap.sh
- integration_tests/happy_path_test.go
- integration_tests/setup_test.go
- orchestrator/cosmos_gravity/src/build.rs
This fixes a couple issues in the multi-EVM integration test, still some more kinks to work out in a follow-up. Had added some checking of `SignerSetTx` to happy path to check the bootstrap conditions and left it in there, delete it if you want.
> Debugging the multi-EVM integration test

- integration_tests/setup_test.go
- integration_tests/validator_out.go
- module/app/app.go
- orchestrator/cosmos_gravity/src/build.rs
- orchestrator/cosmos_gravity/src/send.rs
During stress testing, we observed certain conditions where the Ethereum oracle could get stuck based on the way messages were being chunked together: if the grouping of a chunk included a failed message with ones that should have succeeded, it could skip those valid messages. In this update, when a message batch fails atomically, each individual message from that batch will be retried individually. Thus, if a slow oracle pushes a set of failing messages (e.g. duplicates of previously sent messages) in front of ones that should succeed, it will still attempt to process them all and successfully move the recorded event nonce forward.
There are a few other fixes included here:
1. There was a clash between the transaction stress test and the validator out test -- the globally low value for …
> Prevent cosmos messaging getting stuck

- orchestrator/Cargo.toml
- orchestrator/cosmos_gravity/Cargo.toml
- orchestrator/gorc/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
Bump cargo versions to 2.0.4 for affected packages.
> Cargo version bumps

- module/x/gravity/client/cli/query.go
Fixes the bug mentioned in the Sommelier repo issue here: https://github.com/PeggyJV/sommelier/issues/112
> Use ExactArgs for unbatched-send-to-ethereums cli command

- module/x/gravity/types/types_test.go
This PR changes the expected value for the `TestValsetConfirmHash` unit test.
The previous PR was mistakenly merged with a failing unit test. The unit test takes a valset, generates a checkpoint, and verifies the result matches an expected value. In order to ensure that the failure was due to an incorrect expected value and not an incorrect comparison implementation, I took the following steps:
It turns out that there is a very similar unit test in the `gravity_utils` crate that uses the same test values, but does no sorting. This made it easy to manually verify the expected value. I simply added sorting and checked the output hash, verifying that it matched the new actual value output by the Go unit test.
[The failing Go unit test](https://github.com/PeggyJV/gravity-bridge/blob/c8157e9cd5 …
> Update unit test to use correct expected value

- orchestrator/Cargo.lock
Steward is breaking in dev when I pull in a version of `somm_proto` that includes the pubsub bindings in the axelar-v2 branch. This is happening despite the fact that there is *no* diff between the lock files on `main` and `axelar-v2`:
```
error: failed to select a version for `http`.
... required by package `axum v0.6.9`
... which satisfies dependency `axum = "^0.6.9"` of package `tonic v0.9.0`
... which satisfies dependency `tonic = "^0.9"` of package `cosmos-sdk-proto v0.19.0 (http://github.com/cosmos/cosmos-rust?branch=main#aef5c708)`
... which satisfies git dependency `cosmos-sdk-proto` of package `somm_proto v5.0.0 (https://github.com/peggyjv/sommelier?branch=axelar-v2#fe273124)`
... which satisfies git dependency `somm_proto` of package `steward v3.0.0 …
```
> Update http crate dependency

- integration_tests/go.mod
- integration_tests/go.sum
- module/go.mod
- module/go.sum
On SDK 0.46.14 we should no longer need the ics23 replace directive. It should not be necessary for versions past 0.46.8, see also: https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.8
> Remove old ics23 replace directive

- .github/workflows/integration-tests.yml
- orchestrator/Cargo.lock
- orchestrator/Cargo.toml
- orchestrator/gorc/Cargo.toml
- orchestrator/orchestrator/Cargo.toml
- orchestrator/relayer/Cargo.toml
Bump Cargo versions for 4.0 release.
> gravity_bridge/orchestrator/gorc/relayer to 4.0.0

- module/x/gravity/keeper/batch.go
- module/x/gravity/keeper/batch_test.go
- module/x/gravity/keeper/contract_call.go
- module/x/gravity/keeper/contract_call_test.go
- module/x/gravity/keeper/grpc_query_test.go
- module/x/gravity/keeper/msg_server.go
Adds an additional lookup to check if the signature is targeting an already-completed outgoing tx. 
I verified manually that this fixes the issue with the following steps:
1. Start the happy path test
2. Turn off orchestrator 3 as soon as it is started
3. Stop the test after the SendToEthereum is submitted
4. Watch another orchestrator's log until the batch is submitted
5. Query signatures to confirm there are 3
6. Turn orchestrator 3 back on
7. Observe 4th signature submission
Closes #555
> Fix SubmitEthereumTxConfirmation bug
